[package]
name = "rrt"
version = "0.1.0"
authors = ["Aapo Vienamo <aapo.vienamo@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
